apiVersion: v1
kind: Secret
metadata:
  name: app-config
type: Opaque 
data:
  # Base64 encoded credentials
  # Base64 encoded value of your MYSQL_ROOT_PASSWORD
  # e.g., echo -n "password" | base64
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA==
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: cGFzc3dvcmQ=